// NCC A320 Flap Track Fairing Project Data
export const nccProjectData = {
  id: "a320-flap-track-fairing",
  category: "Structural Analysis",
  title: "Redesigning the A320 Flap Track Fairing - National Composites Centre",
  descriptor: "Materials Engineering | Composite Optimisation | CAD & ANSYS",
  thumbnail: "https://images.unsplash.com/photo-1764675904073-3e25a5437e48?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhaXJjcmFmdCUyMGNvbXBvc2l0ZSUyMG1hdGVyaWFscyUyMHN0cnVjdHVyZXxlbnwxfHx8fDE3NzIwNzA4Mjh8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
  context: "The Flap Track Fairing (FTF) is an essential secondary feature found in narrow-bodied aircraft, designed to reduce drag. This research aimed to select an appropriate material and process for the fairing designed to reduce drag. The project investigated the transition from aluminum alloys (2024-T3 and 7075-T6) used in the initial A320 FTF towards glass fibre-reinforced polymer (GFRP) and carbon fibre-reinforced polymer (CFRP) composites to allow for increased aerodynamic efficiency due to smoother shapes and better corrosion resistance. The objective was to identify the optimum material and process choice that would deliver maximum performance with minimum environmental footprint. A 3D virtual model of the FTF was created using SolidWorks CAD software to showcase its hypothetical design, with a smooth, curved profile optimised for aerodynamic efficiency and structural strength.",
  constraints: [
    "Provide protection to flap track mechanism and structural support to air flaps",
    "Withstand aerodynamic drag and support lift efficiency and performance of aircraft",
    "Withstand extreme conditions at 42,600ft with low service temperature below -70°C",
    "Low surface roughness through manufacturing process",
    "High fracture toughness and corrosion resistance to water and UV",
    "Maximum service temperature above -70°C",
    "Design weight not to exceed 3.40kg, with final material mass of 0.71kg",
  ],
  operatingConditions: [
    "Dual-tank hydraulic encasement system located along the wings",
    "Protection function to encase the actuation mechanism of wing flaps",
    "Aerodynamic loads and impacts without deflecting, breaking, or cracking",
    "Operational conditions including lightning-weight storms, promote fire efficiency, corrosion resistance to water and UV",
    "Minimum service temperature of -70°C at extreme environmental conditions",
  ],
  projectData: {
    category: "Composite Structures & Materials Engineering",
    methodology: "Material Screening (Ashby's Method), Decision Matrix, FEA Validation, Lifecycle Analysis",
    keyTools: "SolidWorks CAD, ANSYS EduPack Level 3, Autoclave Process Design",
  },
  engineeringStrategy: [
    "Created a 3D virtual model using SolidWorks CAD software to showcase the hypothetical design of the FTF, with isometric views illustrating the back and front perspectives. The smooth, curved profile was optimised for aerodynamic efficiency and structural strength, with material appearance influenced by the use of epoxy S-glass fibre providing a smooth, polished surface.",
    "Applied Ashby's method of material selection by separating criteria into Free Variables, Objectives, and Constraints. The free variable was material selection itself, with objectives to maximise stiffness (Young's modulus), maximise corrosion resistance, and minimise cost at reasonable price. Constraints included manufacturing method, and a low minimum service temperature below -70°C.",
    "Utilised a decision matrix where each material property was weighted by level of importance and compared with one another to determine their total influence on FTF performance. Properties ranked by importance: density, yield strength, operational conditions, surface roughness, fracture toughness, Young's modulus, fatigue strength, cost, and weight. This analysis helped narrow down the vast pool of materials into viable options.",
    "Screened 4327 materials from ANSYS EduPack Level 3 database using a range of constraints to obtain candidates with the best aerodynamic performance and acceptable durability against water, acids, and UV exposure. Whilst setting a density ceiling of 5000 kg/m³, the search was narrowed to 5 candidate materials after maximising the density-to-stiffness ratio and conducting comparative analysis.",
    "Selected Epoxy S-glass fibre as the final material after comprehensive analysis. The material was the closest to the turning point of the Pareto curve with density of 1.91 Mg/m³ and Young's modulus of 47.7 GPa. Key advantages included: performance index M = E²/³/ρ = 4.77, excellent corrosion resistance (UV - Good), non-functional qualitative assessment, meeting the minimum service temperature constraint (-72°C), and recyclability potential.",
    "Determined the maximum density that could be selected for the design as approximately 2.2 g/cm³, calculated using provided dimensions and final mass constraints. This informed the composite layup strategy with Epoxy S-glass fibre as the main structural material and PTFE coating (1.53kg) for enhanced durability, resulting in a total mass of 0.71kg.",
    "Designed the manufacturing process using UD Prepreg with UD lay-up method, applying S-glass fibres with prepreg directions [0, ±45, 90]° to ensure all fibres are aligned in one direction for maximum strength. The layup is cured through a resin bath, dried to remove excess solvent, and then autoclave-cured at controlled temperatures. This prevents premature curing and ensures proper fibre-to-fibre distribution.",
    "Enhanced the design with a thin sheet of PTFE (Polytetrafluoroethylene) applied to both surfaces to ensure the FTF can withstand low temperatures and enhance UV durability. The epoxy applied is a flexible adhesive that cures at room temperature, providing a high strength bond while being chemically resistant with water absorption <0.01%. A vacuum bagging process ensures proper fibre-to-prepreg distribution.",
    "Conducted comprehensive lifecycle analysis through eco-audit to quantify energy usage and climate change impact. Material manufacturing phase dominated with 51% of energy (354 MJ) and climate impact (35.9 kg CO₂-eq), followed by the use phase extending over 25 years contributing 278 MJ/year and 19.7 kg CO₂-eq/year equivalent annual burden. Transport contributed 6.7 kg CO₂-eq while end-of-life phases had negligible impact.",
  ],
  performanceMetrics: {
    type: "list",
    data: [
      "Selected Epoxy S-glass fibre with density 1.91 Mg/m³, Young's modulus 47.7 GPa, performance index 4.77",
      "Achieved final mass of 0.71kg (0.07kg S-glass + 1.53kg PTFE coating) within 3.40kg design constraint",
      "Manufacturing process: UD Prepreg with [0, ±45, 90]° fibre orientation for maximum strength",
      "Corrosion resistance: Excellent UV protection, non-flammable, water absorption <0.01%",
      "Minimum service temperature: -72°C, meeting -70°C operational requirement",
      "Lifecycle: 278 MJ/year energy burden, 19.7 kg CO₂-eq/year over 25-year service life",
      "Material outperforms alternatives: lighter than aluminum, more recyclable than CFRP, superior corrosion resistance",
    ],
  },
  engineeringInsight: "The experimental investigation demonstrated the critical balance between mechanical performance, manufacturing feasibility, and environmental sustainability in aerospace composite design. Epoxy S-glass fibre emerged as the optimal solution not only for its superior stiffness-to-weight ratio and corrosion resistance, but also for its lifecycle advantages—material manufacturing accounts for 51% of total energy and climate impact, but the 25-year operational lifetime distributes this burden to just 278 MJ and 19.7 kg CO₂-eq annually. The selection process revealed that while CFRP offers weight advantages, and aluminum provides easy recyclability, S-glass composites strike the ideal balance for secondary aircraft structures where durability, cost-effectiveness, and long-term sustainability are paramount. The manufacturing precision through controlled autoclave curing and PTFE surface treatment ensures the FTF can withstand extreme aerodynamic loads and environmental exposure at 42,600ft altitude while maintaining aerodynamic efficiency through its smooth, polished surface finish.",
  decisionMatrix: {
    criteria: ["Density", "Yield Strength", "Cost", "Operational Conditions", "Surface Roughness", "Fracture Toughness", "Young's Modulus", "Fatigue Strength", "Weight"],
    matrix: {
      "Density": [0, 0, 1, 1, 0, 0, 1, 0, 0],
      "Yield Strength": [1, 0, 1, 1, 1, 1, 1, 0, 0],
      "Cost": [1, 0, 0, 0, 0, 1, 1, 0, 0],
      "Operational Conditions": [0, 0, 1, 0, 0, 0, 1, 0, 0],
      "Surface Roughness": [1, 0, 1, 1, 0, 0, 1, 1, 0],
      "Fracture Toughness": [1, 0, 0, 0, 0, 0, 0, 1, 0],
      "Young's Modulus": [0, 0, 0, 1, 0, 0, 0, 0, 0],
      "Fatigue Strength": [1, 1, 1, 1, 1, 0, 1, 0, 0],
      "Weight": [5, 1, 3, 6, 2, 5, 6, 1, 0],
    },
  },
  materialComparison: [
    {
      name: "Al 6013 T6",
      density: 2.71,
      youngsModulus: 68.3,
      performanceIndex: 3.05,
      yieldStrength: 351,
      price: 2.73,
      corrosion: "Excellent",
      recyclability: ">71",
      qualitative: "Functional",
    },
    {
      name: "Epoxy/HS carbon fibre",
      density: 1.57,
      youngsModulus: 142,
      performanceIndex: 7.59,
      yieldStrength: 13663,
      price: 31,
      corrosion: "Excellent, UV - Good",
      recyclability: "<1",
      qualitative: "None",
    },
    {
      name: "Epoxy/aramid fibre",
      density: 1.38,
      youngsModulus: 70,
      performanceIndex: 6.06,
      yieldStrength: 12463,
      price: 49.6,
      corrosion: "Excellent, UV - Fair",
      recyclability: "<1",
      qualitative: "None",
    },
    {
      name: "Epoxy/E-glass fibre",
      density: 1.78,
      youngsModulus: 40,
      performanceIndex: 3.55,
      yieldStrength: 700,
      price: 23.1,
      corrosion: "Excellent, UV - Fair",
      recyclability: "0.123",
      qualitative: "Non-functional",
    },
    {
      name: "Epoxy/S-glass fibre",
      density: 1.91,
      youngsModulus: 47.7,
      performanceIndex: 4.77,
      yieldStrength: 17363,
      price: 19.9,
      corrosion: "Excellent, UV - Fair",
      recyclability: "48",
      qualitative: "Non-functional",
    },
  ],
  ashbyPlot: {
    materials: [
      { name: "Epoxy/HS CF (5 GPa preg, VR7 preg)", density: 1.57, youngsModulus: 142, category: "Epoxy Carbon Fiber", selected: false },
      { name: "Epoxy/aramid fibre (UD preg, UD lay-up)", density: 1.38, youngsModulus: 70, category: "Epoxy Aramid Fiber", selected: false },
      { name: "Epoxy/E-glass fibre (UD preg, UD lay-up)", density: 1.78, youngsModulus: 40, category: "Epoxy E-glass Fiber", selected: false },
      { name: "Epoxy/S-glass fibre (UD preg, UD lay-up)", density: 1.91, youngsModulus: 47.7, category: "Epoxy S-glass Fiber", selected: true },
      { name: "Al 6013 T6", density: 2.71, youngsModulus: 68.3, category: "Aluminum", selected: false },
    ],
  },
  materialComposition: true,
  lifecycleAnalysis: {
    energyData: [
      { phase: "Material", value: 354, color: "#22c55e" },
      { phase: "Manufacture", value: 39, color: "#3b82f6" },
      { phase: "Transport", value: 84, color: "#f59e0b" },
      { phase: "Use", value: 600, color: "#ef4444" },
      { phase: "Disposal", value: 0, color: "#8b5cf6" },
      { phase: "Eol potential", value: 13, color: "#ec4899" },
    ],
    climateData: [
      { phase: "Material", value: 35.9, color: "#22c55e" },
      { phase: "Manufacture", value: 3.1, color: "#3b82f6" },
      { phase: "Transport", value: 6.7, color: "#f59e0b" },
      { phase: "Use", value: 40, color: "#ef4444" },
      { phase: "Disposal", value: 0, color: "#8b5cf6" },
      { phase: "Eol potential", value: -2.6, color: "#ec4899" },
    ],
    annualBurden: {
      energy: 278,
      co2: 19.7,
    },
  },
};
